- name: maclandrol
  email: emmanuel.noutahi@hotmail.ca
  num_commits: 1
  first_commit: 2021-04-06 11:53:10
- name: Cas Wognum
  email: caswognum@outlook.com
  aliases:
    - cwognum
- name: Hadrien Mary
  email: hadrien.mary@gmail.com
  alternate_emails:
    - hadim@users.noreply.github.com
